[providers]
node = "20"

[phases.install]
cmds = ["cd api && npm install"]

[phases.build]
cmds = ["cd api && npx prisma generate --schema=./prisma/schema.prisma", "cd api && npm run build"]

[start]
cmd = "cd api && npm start"
